NB_LIGNE = 25
NB_COLONNE = 50

MAX_AGE_PRED = 2000
NB_JRS_PUBERTE_PRED = 90
NB_JRS_GESTATION_PRED = 30
MIN_SANTE_PRED = 0
AJOUT_ENERGIE = 3
MIN_ENERGIE = 15

MAX_AGE_PROIE = 100
NB_JRS_PUBERTE_PROIE = 15
NB_JRS_GESTATION_PROIE = 9
NB_MAX_PROIES = NB_LIGNE * NB_COLONNE / 2
POURCENTAGE_CASES_PROIES = 0.5
POURCENTAGE_CASES_PREDATEURS = 0.05

MAX_ITERATION = 10000
DUREE_CYCLE = 500  # Millisecondes
DUREE_AVANT_REDEMARRAGE = 5000  # Millisecondes
